# Generated by Django 4.2.3 on 2023-07-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название комманды(игрового клуба)')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название спорта')),
            ],
        ),
        migrations.CreateModel(
            name='Status_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='статус игры')),
            ],
        ),
        migrations.CreateModel(
            name='Сountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название комманды(игрового клуба)')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя спортсмена')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия спортсмена спортсмена')),
                ('rate', models.IntegerField(verbose_name='рейтинг')),
                ('games_count', models.IntegerField(default=0, verbose_name='кол-во игр')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport', verbose_name='вид спорта')),
                ('сountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.сountry', verbose_name='страна спортсмена')),
            ],
        ),
        migrations.CreateModel(
            name='Game_start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cof1', models.IntegerField(default=0, verbose_name='коф.победы 1 комманды')),
                ('cof2', models.IntegerField(default=0, verbose_name='коф.победы 2 комманды')),
                ('time_start', models.DateTimeField(verbose_name='время начала матча')),
                ('one_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_starts_one', to='sport.command', verbose_name='комманда 1')),
                ('status_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.status_game', verbose_name='Статус игры')),
                ('two_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_starts_two', to='sport.command', verbose_name='комманда 2')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='game_structure',
            field=models.ManyToManyField(to='sport.sportsman', verbose_name='состав команды'),
        ),
        migrations.AddField(
            model_name='command',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport', verbose_name='вид спорта'),
        ),
        migrations.AddField(
            model_name='command',
            name='сountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.сountry', verbose_name='страна'),
        ),
    ]
