# Generated by Django 4.2.3 on 2023-07-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('title',), 'verbose_name': 'комманда', 'verbose_name_plural': 'комманды'},
        ),
        migrations.AlterModelOptions(
            name='game_start',
            options={'ordering': ('one_command', 'two_command'), 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('title',), 'verbose_name': 'вид спорта', 'verbose_name_plural': 'виды спорта'},
        ),
        migrations.AlterModelOptions(
            name='sportsman',
            options={'ordering': ('name',), 'verbose_name': 'спортсмен', 'verbose_name_plural': 'спортсмены'},
        ),
        migrations.AlterModelOptions(
            name='status_game',
            options={'ordering': ('title',), 'verbose_name': 'статус игры', 'verbose_name_plural': 'статус игр'},
        ),
        migrations.AlterModelOptions(
            name='сountry',
            options={'ordering': ('title',), 'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
    ]
