# Generated by Django 4.2.4 on 2023-09-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_user_transaction_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='баланс пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bet_counter',
            field=models.IntegerField(default=0, verbose_name='сделано ставок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bet_wins',
            field=models.IntegerField(default=0, verbose_name='победных ставок'),
        ),
    ]
