# Generated by Django 4.2.4 on 2023-09-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_user_balance_alter_user_bet_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='пользователь')),
                ('balance', models.IntegerField(default=0, verbose_name='баланс пользователя')),
                ('bet_counter', models.IntegerField(default=0, editable=False, verbose_name='сделано ставок')),
                ('bet_wins', models.IntegerField(default=0, editable=False, verbose_name='победных ставок')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('username',),
            },
        ),
        migrations.AddField(
            model_name='game_start',
            name='winners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.command', verbose_name='победила комманда'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.useraccount', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.useraccount', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
