# Generated by Django 4.2.4 on 2023-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_useraccount_game_start_winners_alter_bet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bet_counter',
            field=models.IntegerField(verbose_name='сделано ставок'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='bet_wins',
            field=models.IntegerField(verbose_name='победных ставок'),
        ),
    ]
