# Generated by Django 4.2.4 on 2023-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_alter_useraccount_bet_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bet_counter',
            field=models.IntegerField(null=True, verbose_name='сделано ставок'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='bet_wins',
            field=models.IntegerField(null=True, verbose_name='победных ставок'),
        ),
    ]
