# Generated by Django 4.2.4 on 2023-09-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_alter_useraccount_bet_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bet_wins',
            field=models.IntegerField(default=0, null=True, verbose_name='победных ставок'),
        ),
    ]
