# Generated by Django 4.2.4 on 2023-09-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_alter_useraccount_bet_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_start',
            name='cof1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='коф.победы 1 комманды'),
        ),
        migrations.AlterField(
            model_name='game_start',
            name='cof2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='коф.победы 2 комманды'),
        ),
    ]
