# Generated by Django 4.2.4 on 2023-09-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_alter_game_start_cof1_alter_game_start_cof2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
