# Generated by Django 4.2.4 on 2023-09-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_useraccount_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ('user',), 'verbose_name': 'баланс пользователя', 'verbose_name_plural': 'баланс пользователей'},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
