# Generated by Django 4.2.4 on 2023-09-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='rate',
        ),
    ]
