# Generated by Django 4.2.4 on 2023-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_user_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=24, verbose_name='пароль'),
            preserve_default=False,
        ),
    ]
