# Generated by Django 4.2.4 on 2023-09-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0016_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
