# Generated by Django 4.2.4 on 2023-09-11 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0017_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='баланс пользователя')),
                ('bet_counter', models.IntegerField(default=0, null=True, verbose_name='сделано ставок')),
                ('bet_wins', models.IntegerField(default=0, null=True, verbose_name='победных ставок')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('user',),
            },
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.userprofile', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
